{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ml-project.namespace" . }}
  labels:
    {{- include "ml-project.labels" . | nindent 4 }}
    mlops.platform/tier: project
{{- end }}
