{{- if and .Values.components.training (not .Values.schedule.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ml-project.name" . }}-train
  namespace: {{ include "ml-project.namespace" . }}
  labels:
    {{- include "ml-project.labels" . | nindent 4 }}
    mlops.platform/component: training
spec:
  backoffLimit: {{ .Values.training.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "ml-project.labels" . | nindent 8 }}
        mlops.platform/component: training
    spec:
      serviceAccountName: {{ include "ml-project.serviceAccountName" . }}
      restartPolicy: {{ .Values.training.restartPolicy }}
      containers:
        - name: train
          image: {{ .Values.image.training | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.training.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "ml-project.name" . }}-config
          {{- with .Values.training.env }}
          env:
            {{- range $k, $v := . }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.training | nindent 12 }}
{{- end }}
