{{- if and .Values.components.training .Values.schedule.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ml-project.name" . }}-train
  namespace: {{ include "ml-project.namespace" . }}
  labels:
    {{- include "ml-project.labels" . | nindent 4 }}
    mlops.platform/component: training
spec:
  schedule: {{ .Values.schedule.cron | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.training.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "ml-project.labels" . | nindent 12 }}
            mlops.platform/component: training
        spec:
          serviceAccountName: {{ include "ml-project.serviceAccountName" . }}
          restartPolicy: {{ .Values.training.restartPolicy }}
          containers:
            - name: train
              image: {{ .Values.image.training | quote }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                {{- toYaml .Values.training.command | nindent 16 }}
              envFrom:
                - configMapRef:
                    name: {{ include "ml-project.name" . }}-config
              resources:
                {{- toYaml .Values.resources.training | nindent 16 }}
{{- end }}
