platform:
  name: mlops-platform
  environment: prod

resourceQuota:
  enabled: true
  hard:
    requests.cpu: "40"
    requests.memory: 80Gi
    limits.cpu: "80"
    limits.memory: 160Gi
    pods: "500"
    persistentvolumeclaims: "100"

networkPolicy:
  enabled: true
  defaultDeny: true

argoProject:
  create: true
  name: mlops
