apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mlops-readmes-mcp
  labels:
    app: mlops-readmes-mcp
spec:
  to:
    kind: Service
    name: mlops-readmes-mcp
  port:
    targetPort: http
  tls:
    termination: edge
