apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ml-project.name" . }}-config
  namespace: {{ include "ml-project.namespace" . }}
  labels:
    {{- include "ml-project.labels" . | nindent 4 }}
data:
  PROJECT_NAME: {{ include "ml-project.name" . | quote }}
  PROJECT_TEAM: {{ .Values.project.team | quote }}
  PROJECT_ENV: {{ .Values.project.environment | quote }}
  PROJECT_DESCRIPTION: {{ .Values.project.description | quote }}
  {{- if .Values.components.mlflow }}
  MLFLOW_TRACKING_URI: {{ .Values.mlflow.trackingUri | quote }}
  {{- end }}
