{{- if .Values.argoProject.create }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.argoProject.name }}
  namespace: argocd
  labels:
    {{- include "mlops-main.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ .Values.argoProject.description | quote }}
  sourceRepos:
    {{- toYaml .Values.argoProject.sourceRepos | nindent 4 }}
  destinations:
    {{- toYaml .Values.argoProject.destinations | nindent 4 }}
  clusterResourceWhitelist:
    {{- toYaml .Values.argoProject.clusterResourceWhitelist | nindent 4 }}
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
{{- end }}
