{{- if .Values.resourceQuota.enabled }}
{{- range $key, $ns := .Values.namespaces }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-quota
  namespace: {{ $ns.name }}
  labels:
    {{- include "mlops-main.labels" $ | nindent 4 }}
spec:
  hard:
    {{- toYaml $.Values.resourceQuota.hard | nindent 4 }}
{{- end }}
{{- end }}
