platform:
  name: mlops-platform
  environment: dev

namespaces:
  system:
    name: mlops-system
  shared:
    name: mlops-shared
  monitoring:
    name: mlops-monitoring

resourceQuota:
  enabled: true
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    pods: "100"
    persistentvolumeclaims: "30"

networkPolicy:
  enabled: true
  defaultDeny: false

argoProject:
  create: true
  name: mlops
